version: '3'
services:
  support-ticket-microservice:
    build: .
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb+srv://ahmed:ahmed@cluster0.lzabahv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=eb389bd4ca05e4bbec0702de76fcc1cf6d89fd0e5f3055e0dc0befaa16bd7132066060cb1b1c5fb4535da0b876e0cd255b7742a5f21514307b4c868a3072f632
      - EMAIL=swiftparcel999@gmail.com
      - PASSWORD=olrjowqgtxoeckuk
